<?php
# medwiki LocalSettings.php
# This file was automatically generated by the MediaWiki 1.43.0-alpha
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/MainConfigSchema.php for all configurable settings
# and their default values, but don"t forget to make changes in _this_
# file, not there.

#
# Further documentation for configuration settings may be found at:
# https://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if (!defined("MEDIAWIKI")) {
    exit;
}
// if (isset($_GET['test'])) {
//     ini_set('display_errors', 1);
//     ini_set('display_startup_errors', 1);
//     error_reporting(E_ALL);
//     $wgShowExceptionDetails = false;
//     $wgShowDBErrorBacktrace = false;
//     $wgShowSQLErrors = false;
// };

//$wgEnableJavaScriptTest = true;
// temp $wgGroupPermissions["*"]["edit"] = false;
$wgGroupPermissions["*"]["createpage"] = false;

$wgGroupPermissions["autoconfirmed"]["edit"] = true;
$wgGroupPermissions["bot"]["edit"] = true;
$wgGroupPermissions["user"]["edit"] = true;

$wgGroupPermissions["autoconfirmed"]["createpage"] = true;
$wgGroupPermissions["bot"]["createpage"] = true;
$wgGroupPermissions["user"]["createpage"] = true;

$wgGroupPermissions["*"]["skipcaptcha"] = true;


// Define constants for my additional namespaces.
define("NS_Md", 30); // This MUST be even.
define("NS_Md_TALK", 31); // This MUST be the following odd integer.

// Add namespaces.
$wgExtraNamespaces[NS_Md] = "Md";
$wgExtraNamespaces[NS_Md_TALK] = "Md_talk"; // Note underscores in the namespace name.

// $wgNamespaceProtection[NS_Md] = ["Md-edit"];
// $wgGroupPermissions["interface-admin"]["Md-edit"] = true;
// $wgGroupPermissions["sysop"]["Md-edit"] = true;
// $wgGroupPermissions["bureaucrat"]["Md-edit"] = true;
// $wgGroupPermissions["suppress"]["Md-edit"] = true;

// $wgSuspiciousIpExpiry =
$wgImportSources = [
    "wikipedia" => ["en"]
];

$wgRememberMe = "always";

$wgAllowCrossOrigin = true;

$wgCrossSiteAJAXdomains = [
    "*.toolforge.org",
    "*.nccommons.org",
    "*.mdwiki.org",
    "*.wikimedia.org",
    "*.wmcloud.org"
];

## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename = "Translation Tool";
$wgMetaNamespace = "Project";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs
## (like /w/index.php/Page_title to /wiki/Page_title) please see:
## https://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath = "/w";
$wgArticlePath = "/wiki/$1";
// $wgUsePathInfo = true;


## The protocol and server name to use in fully-qualified URLs
$wgServer = "https://medwiki.toolforge.org";

## The URL path to static resources (images, scripts, etc.)
$wgResourceBasePath = $wgScriptPath;

## The URL paths to the logo.  Make sure you change this from the default,
## or else you'll overwrite your logo when you upgrade!
$wgLogos = [
    "1x" => "$wgResourceBasePath/resources/assets/logo.svg",
    "icon" => "$wgResourceBasePath/resources/assets/logo.svg",
];

## UPO means: this is also a user preference option

$wgEnableEmail = true;
$wgEnableUserEmail = true; # UPO

$wgEmergencyContact = "";
$wgPasswordSender = "";

$wgEnotifUserTalk = false; # UPO
$wgEnotifWatchlist = false; # UPO
$wgEmailAuthentication = true;

## Database settings
$wgDBtype = "mysql";
$wgDBserver = "!!";
$wgDBname = "!!";
$wgDBuser = "!!";
$wgDBpassword = "!!";

# MySQL specific settings
$wgDBprefix = "";
$wgDBssl = true;

# MySQL table options to use during installation or update
$wgDBTableOptions = "ENGINE=InnoDB, DEFAULT CHARSET=binary";

# Shared database table
# This has no effect unless $wgSharedDB is also set.
$wgSharedTables[] = "actor";

$wgCookiePrefix = "medwiki_w_";

## Shared memory settings
$wgMainCacheType = CACHE_ACCEL;
$wgMemCachedServers = [];

## To enable image uploads, make sure the "images" directory
## is writable, then set this to true:
$wgEnableUploads = false;
#$wgUseImageMagick = true;
#$wgImageMagickConvertCommand = "/usr/bin/convert";

# InstantCommons allows wiki to use images from https://commons.wikimedia.org
$wgUseInstantCommons = true;

# Periodically send a pingback to https://www.mediawiki.org/ with basic data
# about this MediaWiki instance. The Wikimedia Foundation shares this data
# with MediaWiki developers to help guide future development efforts.
$wgPingback = false;

# Site language code, should be one of the list in ./includes/languages/data/Names.php
$wgLanguageCode = "en";

# Time zone
$wgLocaltimezone = "UTC";

## Set $wgCacheDirectory to a writable directory on the web server
## to make your wiki go slightly faster. The directory should not
## be publicly accessible from the web.
$wgCacheDirectory = "";

$wgSecretKey = "";

# Changing this will log out all existing sessions.
$wgAuthenticationTokenVersion = "1";

# Site upgrade key. Must be set to a string (default provided) to turn on the
# web installer while LocalSettings.php is in place
$wgUpgradeKey = "";

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = "https://creativecommons.org/licenses/by/4.0/";
$wgRightsText = "reative Commons Attribution";
$wgRightsIcon = "$wgResourceBasePath/resources/assets/licenses/cc-by.png";

# Path to the GNU diff3 utility. Used for conflict resolution.
$wgDiff3 = "/usr/bin/diff3";

## Default skin: you can change the default skin. Use the internal symbolic
## names, e.g. "vector" or "monobook":
$wgDefaultSkin = "vector";
$wgGroupPermissions["user"]["writeapi"] = true;

# Enabled skins.
# The following skins were automatically enabled:
wfLoadSkin("Vector");


# Enabled extensions. Most of the extensions are enabled by adding
# wfLoadExtension( "ExtensionName" );
# to LocalSettings.php. Check specific extension documentation for more details.
# The following extensions were automatically enabled:

wfLoadExtension("BetaFeatures");
wfLoadExtension("Cite");
wfLoadExtension("CodeEditor");
wfLoadExtension("ContentTranslation");
wfLoadExtension("DiscussionTools");
wfLoadExtension("Echo");
wfLoadExtension("Gadgets");
wfLoadExtension("Interwiki");
wfLoadExtension("Linter");
wfLoadExtension("LoginNotify");
wfLoadExtension("Math");
wfLoadExtension("MultimediaViewer");
wfLoadExtension("Nuke");
wfLoadExtension("ParserFunctions");
wfLoadExtension("PluggableAuth");
wfLoadExtension("ReplaceText");
wfLoadExtension("Scribunto");
wfLoadExtension("SyntaxHighlight_GeSHi");
wfLoadExtension("TemplateData");
wfLoadExtension("TemplateStyles");
wfLoadExtension("TextExtracts");
wfLoadExtension("Thanks");
wfLoadExtension("UniversalLanguageSelector");
wfLoadExtension("UnlinkedWikibase");
wfLoadExtension("VisualEditor");
wfLoadExtension("WSOAuth");
wfLoadExtension("WikiEditor");
//wfLoadExtension( "AbuseFilter" );

$wgDefaultUserOptions["usebetatoolbar"] = 1; // user option provided by WikiEditor extension
$wgGroupPermissions["sysop"]["interwiki"] = true;
// $wgInterwikiCentralDB = "mw_central";


$wgGroupPermissions["*"]["createaccount"] = true;
$wgGroupPermissions["*"]["autocreateaccount"] = true;

$wgPluggableAuth_Config["mywikiauth"] = [
    "plugin" => "WSOAuth",
    "data" => [
        "type" => "mediawiki",
        "uri" => "https://meta.wikimedia.org/w/index.php?title=Special:OAuth",
        "clientId" => "",
        "clientSecret" => "",
        "redirectUri" => "https://medwiki.toolforge.org/w/index.php?title=Special:PluggableAuthLogin"
    ],
    "buttonLabelMessage" => "SSOButtonLabel"
];

// $wgPluggableAuth_EnableAutoLogin = true;
$wgPluggableAuth_EnableLocalLogin = false;

$wgScribuntoUseGeSHi = true;
$wgScribuntoUseCodeEditor = true;
$wgScribuntoEngineConf["luastandalone"]["memoryLimit"] = 509715200; # bytes

// $wgScribuntoDefaultEngine = "luastandalone";
$wgUnlinkedWikibaseBaseUrl = "https://www.wikidata.org/wiki/";
$wgUnlinkedWikibaseBaseQueryEndpoint = "https://query.wikidata.org/bigdata/namespace/wdq/sparql";

$wgUnlinkedWikibaseStatementsParserFunc = true;
//$wgUnlinkedWikibaseEntityTTL = null;

$wgUnlinkedWikibaseSitelinkSuffix = "wiki";

$wgUnlinkedWikibaseSitelinkSkippedLangs = [
    "commonswiki",
];


$wgAllowUserJs = true;
$wgAllowUserCss = true;
$wgAllowUserCssPrefs = true;

$wgContentTranslationAsBetaFeature = false;
$wgContentTranslationUnmodifiedMTThresholdForPublish = 100;
$wgContentTranslationEnableSectionTranslation = false;
$wgContentTranslationEnableMT = true;
$wgContentTranslationPublishRequirements = [
    "userGroups" => [
        "*"
    ]
];

$wgContentTranslationCampaigns = [
    "Main" => true,
    "COVID" => true,
    "Hearing" => true,
    "Occupational Health" => true,
    "Essential Medicines" => true,
    "Women Health" => true,
    "Epilepsy" => true
];

$wgContentTranslationSiteTemplates_mdwiki = [
    "view" => "//mdwiki.org/wiki/$2",
    "action" => "//mdwiki.org/w/index.php?title=$2",
    "api" => "/mdwiki_api.php",
    "cx" => "https://cxserver.wikimedia.org/v1",
    "cookieDomain" => null,
    "restbase" => "//mdwiki.org/api/rest_v1"
];

$wgContentTranslationSiteTemplates["cx"] = "https://cxserver.wikimedia.org/v1";

$wgResourceModules["mw.cx.init"]["scripts"][] = "mw.cx.TranslationMdwiki.js";
$wgResourceModules["mw.cx.SiteMapper"]["packageFiles"][1]["config"]["SiteTemplates_mdwiki"] = "ContentTranslationSiteTemplates_mdwiki";

// $wgContentTranslationContentImportForSectionTranslation = ;
// $wgContentTranslationEnableUnifiedDashboard = ;
// $wgContentTranslationTranslateInTarget = true;

$wgExtraLanguageNames["mdwiki"] = "mdwiki";
$wgExtraLanguageNames["nr"] = "isiNdebele seSewula";
